# Generated by Django 2.1.5 on 2019-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='Table №<built-in function id>', max_length=20),
        ),
    ]
