# Generated by Django 2.1.5 on 2019-01-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_auto_20190114_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='Table №', max_length=20, unique=True),
        ),
    ]
