# Generated by Django 2.1.5 on 2019-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_auto_20190114_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AlterField(
            model_name='table',
            name='length',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='places',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('OVAL', 'oval'), ('SQUERE', 'squere')], default='oval', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
